/**
 * TypeISOCountryCodeA3.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.ipcommerce.schemas.CWS.v2_0.ServiceInformation;

public class TypeISOCountryCodeA3 implements java.io.Serializable {
    private java.lang.String _value_;
    private static java.util.HashMap _table_ = new java.util.HashMap();

    // Constructor
    protected TypeISOCountryCodeA3(java.lang.String value) {
        _value_ = value;
        _table_.put(_value_,this);
    }

    public static final java.lang.String _NotSet = "NotSet";
    public static final java.lang.String _AFG = "AFG";
    public static final java.lang.String _ALA = "ALA";
    public static final java.lang.String _ALB = "ALB";
    public static final java.lang.String _DZA = "DZA";
    public static final java.lang.String _ASM = "ASM";
    public static final java.lang.String _AND = "AND";
    public static final java.lang.String _AGO = "AGO";
    public static final java.lang.String _AIA = "AIA";
    public static final java.lang.String _ATA = "ATA";
    public static final java.lang.String _ATG = "ATG";
    public static final java.lang.String _ARG = "ARG";
    public static final java.lang.String _ARM = "ARM";
    public static final java.lang.String _ABW = "ABW";
    public static final java.lang.String _AUS = "AUS";
    public static final java.lang.String _AUT = "AUT";
    public static final java.lang.String _AZE = "AZE";
    public static final java.lang.String _BHS = "BHS";
    public static final java.lang.String _BHR = "BHR";
    public static final java.lang.String _BGD = "BGD";
    public static final java.lang.String _BRB = "BRB";
    public static final java.lang.String _BLR = "BLR";
    public static final java.lang.String _BEL = "BEL";
    public static final java.lang.String _BLZ = "BLZ";
    public static final java.lang.String _BEN = "BEN";
    public static final java.lang.String _BMU = "BMU";
    public static final java.lang.String _BTN = "BTN";
    public static final java.lang.String _BOL = "BOL";
    public static final java.lang.String _BIH = "BIH";
    public static final java.lang.String _BWA = "BWA";
    public static final java.lang.String _BVT = "BVT";
    public static final java.lang.String _BRA = "BRA";
    public static final java.lang.String _IOT = "IOT";
    public static final java.lang.String _BRN = "BRN";
    public static final java.lang.String _BGR = "BGR";
    public static final java.lang.String _BFA = "BFA";
    public static final java.lang.String _BDI = "BDI";
    public static final java.lang.String _KHM = "KHM";
    public static final java.lang.String _CMR = "CMR";
    public static final java.lang.String _CAN = "CAN";
    public static final java.lang.String _CPV = "CPV";
    public static final java.lang.String _CYM = "CYM";
    public static final java.lang.String _CAF = "CAF";
    public static final java.lang.String _TCD = "TCD";
    public static final java.lang.String _CHL = "CHL";
    public static final java.lang.String _CHN = "CHN";
    public static final java.lang.String _CXR = "CXR";
    public static final java.lang.String _CCK = "CCK";
    public static final java.lang.String _COL = "COL";
    public static final java.lang.String _COM = "COM";
    public static final java.lang.String _COG = "COG";
    public static final java.lang.String _COD = "COD";
    public static final java.lang.String _COK = "COK";
    public static final java.lang.String _CRI = "CRI";
    public static final java.lang.String _CIV = "CIV";
    public static final java.lang.String _HRV = "HRV";
    public static final java.lang.String _CUB = "CUB";
    public static final java.lang.String _CYP = "CYP";
    public static final java.lang.String _CZE = "CZE";
    public static final java.lang.String _DNK = "DNK";
    public static final java.lang.String _DJI = "DJI";
    public static final java.lang.String _DMA = "DMA";
    public static final java.lang.String _DOM = "DOM";
    public static final java.lang.String _ECU = "ECU";
    public static final java.lang.String _EGY = "EGY";
    public static final java.lang.String _SLV = "SLV";
    public static final java.lang.String _GNQ = "GNQ";
    public static final java.lang.String _ERI = "ERI";
    public static final java.lang.String _EST = "EST";
    public static final java.lang.String _ETH = "ETH";
    public static final java.lang.String _FLK = "FLK";
    public static final java.lang.String _FRO = "FRO";
    public static final java.lang.String _FJI = "FJI";
    public static final java.lang.String _FIN = "FIN";
    public static final java.lang.String _FRA = "FRA";
    public static final java.lang.String _FXX = "FXX";
    public static final java.lang.String _GUF = "GUF";
    public static final java.lang.String _PYF = "PYF";
    public static final java.lang.String _ATF = "ATF";
    public static final java.lang.String _GAB = "GAB";
    public static final java.lang.String _GMB = "GMB";
    public static final java.lang.String _GEO = "GEO";
    public static final java.lang.String _DEU = "DEU";
    public static final java.lang.String _GHA = "GHA";
    public static final java.lang.String _GIB = "GIB";
    public static final java.lang.String _GRC = "GRC";
    public static final java.lang.String _GRL = "GRL";
    public static final java.lang.String _GRD = "GRD";
    public static final java.lang.String _GLP = "GLP";
    public static final java.lang.String _GUM = "GUM";
    public static final java.lang.String _GTM = "GTM";
    public static final java.lang.String _GGY = "GGY";
    public static final java.lang.String _GIN = "GIN";
    public static final java.lang.String _GNB = "GNB";
    public static final java.lang.String _GUY = "GUY";
    public static final java.lang.String _HTI = "HTI";
    public static final java.lang.String _HMD = "HMD";
    public static final java.lang.String _VAT = "VAT";
    public static final java.lang.String _HND = "HND";
    public static final java.lang.String _HKG = "HKG";
    public static final java.lang.String _HUN = "HUN";
    public static final java.lang.String _ISL = "ISL";
    public static final java.lang.String _IND = "IND";
    public static final java.lang.String _IDN = "IDN";
    public static final java.lang.String _IRN = "IRN";
    public static final java.lang.String _IRQ = "IRQ";
    public static final java.lang.String _IRL = "IRL";
    public static final java.lang.String _IMN = "IMN";
    public static final java.lang.String _ISR = "ISR";
    public static final java.lang.String _ITA = "ITA";
    public static final java.lang.String _JAM = "JAM";
    public static final java.lang.String _JPN = "JPN";
    public static final java.lang.String _JEY = "JEY";
    public static final java.lang.String _JOR = "JOR";
    public static final java.lang.String _KAZ = "KAZ";
    public static final java.lang.String _KEN = "KEN";
    public static final java.lang.String _KIR = "KIR";
    public static final java.lang.String _PRK = "PRK";
    public static final java.lang.String _KOR = "KOR";
    public static final java.lang.String _KWT = "KWT";
    public static final java.lang.String _KGZ = "KGZ";
    public static final java.lang.String _LAO = "LAO";
    public static final java.lang.String _LVA = "LVA";
    public static final java.lang.String _LBN = "LBN";
    public static final java.lang.String _LSO = "LSO";
    public static final java.lang.String _LBR = "LBR";
    public static final java.lang.String _LBY = "LBY";
    public static final java.lang.String _LIE = "LIE";
    public static final java.lang.String _LTU = "LTU";
    public static final java.lang.String _LUX = "LUX";
    public static final java.lang.String _MAC = "MAC";
    public static final java.lang.String _MKD = "MKD";
    public static final java.lang.String _MDG = "MDG";
    public static final java.lang.String _MWI = "MWI";
    public static final java.lang.String _MYS = "MYS";
    public static final java.lang.String _MDV = "MDV";
    public static final java.lang.String _MLI = "MLI";
    public static final java.lang.String _MLT = "MLT";
    public static final java.lang.String _MHL = "MHL";
    public static final java.lang.String _MTQ = "MTQ";
    public static final java.lang.String _MRT = "MRT";
    public static final java.lang.String _MUS = "MUS";
    public static final java.lang.String _MYT = "MYT";
    public static final java.lang.String _MEX = "MEX";
    public static final java.lang.String _FSM = "FSM";
    public static final java.lang.String _MDA = "MDA";
    public static final java.lang.String _MCO = "MCO";
    public static final java.lang.String _MNG = "MNG";
    public static final java.lang.String _MNE = "MNE";
    public static final java.lang.String _MSR = "MSR";
    public static final java.lang.String _MAR = "MAR";
    public static final java.lang.String _MOZ = "MOZ";
    public static final java.lang.String _MMR = "MMR";
    public static final java.lang.String _NAM = "NAM";
    public static final java.lang.String _NRU = "NRU";
    public static final java.lang.String _NPL = "NPL";
    public static final java.lang.String _NLD = "NLD";
    public static final java.lang.String _ANT = "ANT";
    public static final java.lang.String _NCL = "NCL";
    public static final java.lang.String _NZL = "NZL";
    public static final java.lang.String _NIC = "NIC";
    public static final java.lang.String _NER = "NER";
    public static final java.lang.String _NGA = "NGA";
    public static final java.lang.String _NIU = "NIU";
    public static final java.lang.String _NFK = "NFK";
    public static final java.lang.String _MNP = "MNP";
    public static final java.lang.String _NOR = "NOR";
    public static final java.lang.String _OMN = "OMN";
    public static final java.lang.String _PAK = "PAK";
    public static final java.lang.String _PLW = "PLW";
    public static final java.lang.String _PSE = "PSE";
    public static final java.lang.String _PAN = "PAN";
    public static final java.lang.String _PNG = "PNG";
    public static final java.lang.String _PRY = "PRY";
    public static final java.lang.String _PER = "PER";
    public static final java.lang.String _PHL = "PHL";
    public static final java.lang.String _PCN = "PCN";
    public static final java.lang.String _POL = "POL";
    public static final java.lang.String _PRT = "PRT";
    public static final java.lang.String _PRI = "PRI";
    public static final java.lang.String _QAT = "QAT";
    public static final java.lang.String _REU = "REU";
    public static final java.lang.String _ROU = "ROU";
    public static final java.lang.String _RUS = "RUS";
    public static final java.lang.String _RWA = "RWA";
    public static final java.lang.String _SHN = "SHN";
    public static final java.lang.String _KNA = "KNA";
    public static final java.lang.String _LCA = "LCA";
    public static final java.lang.String _SPM = "SPM";
    public static final java.lang.String _VCT = "VCT";
    public static final java.lang.String _WSM = "WSM";
    public static final java.lang.String _SMR = "SMR";
    public static final java.lang.String _STP = "STP";
    public static final java.lang.String _SAU = "SAU";
    public static final java.lang.String _SEN = "SEN";
    public static final java.lang.String _SRB = "SRB";
    public static final java.lang.String _SCG = "SCG";
    public static final java.lang.String _SYC = "SYC";
    public static final java.lang.String _SLE = "SLE";
    public static final java.lang.String _SGP = "SGP";
    public static final java.lang.String _SVK = "SVK";
    public static final java.lang.String _SVN = "SVN";
    public static final java.lang.String _SLB = "SLB";
    public static final java.lang.String _SOM = "SOM";
    public static final java.lang.String _ZAF = "ZAF";
    public static final java.lang.String _SGS = "SGS";
    public static final java.lang.String _ESP = "ESP";
    public static final java.lang.String _LKA = "LKA";
    public static final java.lang.String _SDN = "SDN";
    public static final java.lang.String _SUR = "SUR";
    public static final java.lang.String _SJM = "SJM";
    public static final java.lang.String _SWZ = "SWZ";
    public static final java.lang.String _SWE = "SWE";
    public static final java.lang.String _CHE = "CHE";
    public static final java.lang.String _SYR = "SYR";
    public static final java.lang.String _TWN = "TWN";
    public static final java.lang.String _TJK = "TJK";
    public static final java.lang.String _TZA = "TZA";
    public static final java.lang.String _THA = "THA";
    public static final java.lang.String _TLS = "TLS";
    public static final java.lang.String _TGO = "TGO";
    public static final java.lang.String _TKL = "TKL";
    public static final java.lang.String _TMP = "TMP";
    public static final java.lang.String _TON = "TON";
    public static final java.lang.String _TTO = "TTO";
    public static final java.lang.String _TUN = "TUN";
    public static final java.lang.String _TUR = "TUR";
    public static final java.lang.String _TKM = "TKM";
    public static final java.lang.String _TCA = "TCA";
    public static final java.lang.String _TUV = "TUV";
    public static final java.lang.String _UGA = "UGA";
    public static final java.lang.String _UKR = "UKR";
    public static final java.lang.String _ARE = "ARE";
    public static final java.lang.String _GBR = "GBR";
    public static final java.lang.String _USA = "USA";
    public static final java.lang.String _UMI = "UMI";
    public static final java.lang.String _URY = "URY";
    public static final java.lang.String _UZB = "UZB";
    public static final java.lang.String _VUT = "VUT";
    public static final java.lang.String _VEN = "VEN";
    public static final java.lang.String _VNM = "VNM";
    public static final java.lang.String _VGB = "VGB";
    public static final java.lang.String _VIR = "VIR";
    public static final java.lang.String _WLF = "WLF";
    public static final java.lang.String _ESH = "ESH";
    public static final java.lang.String _YEM = "YEM";
    public static final java.lang.String _YUG = "YUG";
    public static final java.lang.String _ZMB = "ZMB";
    public static final java.lang.String _ZWE = "ZWE";
    public static final TypeISOCountryCodeA3 NotSet = new TypeISOCountryCodeA3(_NotSet);
    public static final TypeISOCountryCodeA3 AFG = new TypeISOCountryCodeA3(_AFG);
    public static final TypeISOCountryCodeA3 ALA = new TypeISOCountryCodeA3(_ALA);
    public static final TypeISOCountryCodeA3 ALB = new TypeISOCountryCodeA3(_ALB);
    public static final TypeISOCountryCodeA3 DZA = new TypeISOCountryCodeA3(_DZA);
    public static final TypeISOCountryCodeA3 ASM = new TypeISOCountryCodeA3(_ASM);
    public static final TypeISOCountryCodeA3 AND = new TypeISOCountryCodeA3(_AND);
    public static final TypeISOCountryCodeA3 AGO = new TypeISOCountryCodeA3(_AGO);
    public static final TypeISOCountryCodeA3 AIA = new TypeISOCountryCodeA3(_AIA);
    public static final TypeISOCountryCodeA3 ATA = new TypeISOCountryCodeA3(_ATA);
    public static final TypeISOCountryCodeA3 ATG = new TypeISOCountryCodeA3(_ATG);
    public static final TypeISOCountryCodeA3 ARG = new TypeISOCountryCodeA3(_ARG);
    public static final TypeISOCountryCodeA3 ARM = new TypeISOCountryCodeA3(_ARM);
    public static final TypeISOCountryCodeA3 ABW = new TypeISOCountryCodeA3(_ABW);
    public static final TypeISOCountryCodeA3 AUS = new TypeISOCountryCodeA3(_AUS);
    public static final TypeISOCountryCodeA3 AUT = new TypeISOCountryCodeA3(_AUT);
    public static final TypeISOCountryCodeA3 AZE = new TypeISOCountryCodeA3(_AZE);
    public static final TypeISOCountryCodeA3 BHS = new TypeISOCountryCodeA3(_BHS);
    public static final TypeISOCountryCodeA3 BHR = new TypeISOCountryCodeA3(_BHR);
    public static final TypeISOCountryCodeA3 BGD = new TypeISOCountryCodeA3(_BGD);
    public static final TypeISOCountryCodeA3 BRB = new TypeISOCountryCodeA3(_BRB);
    public static final TypeISOCountryCodeA3 BLR = new TypeISOCountryCodeA3(_BLR);
    public static final TypeISOCountryCodeA3 BEL = new TypeISOCountryCodeA3(_BEL);
    public static final TypeISOCountryCodeA3 BLZ = new TypeISOCountryCodeA3(_BLZ);
    public static final TypeISOCountryCodeA3 BEN = new TypeISOCountryCodeA3(_BEN);
    public static final TypeISOCountryCodeA3 BMU = new TypeISOCountryCodeA3(_BMU);
    public static final TypeISOCountryCodeA3 BTN = new TypeISOCountryCodeA3(_BTN);
    public static final TypeISOCountryCodeA3 BOL = new TypeISOCountryCodeA3(_BOL);
    public static final TypeISOCountryCodeA3 BIH = new TypeISOCountryCodeA3(_BIH);
    public static final TypeISOCountryCodeA3 BWA = new TypeISOCountryCodeA3(_BWA);
    public static final TypeISOCountryCodeA3 BVT = new TypeISOCountryCodeA3(_BVT);
    public static final TypeISOCountryCodeA3 BRA = new TypeISOCountryCodeA3(_BRA);
    public static final TypeISOCountryCodeA3 IOT = new TypeISOCountryCodeA3(_IOT);
    public static final TypeISOCountryCodeA3 BRN = new TypeISOCountryCodeA3(_BRN);
    public static final TypeISOCountryCodeA3 BGR = new TypeISOCountryCodeA3(_BGR);
    public static final TypeISOCountryCodeA3 BFA = new TypeISOCountryCodeA3(_BFA);
    public static final TypeISOCountryCodeA3 BDI = new TypeISOCountryCodeA3(_BDI);
    public static final TypeISOCountryCodeA3 KHM = new TypeISOCountryCodeA3(_KHM);
    public static final TypeISOCountryCodeA3 CMR = new TypeISOCountryCodeA3(_CMR);
    public static final TypeISOCountryCodeA3 CAN = new TypeISOCountryCodeA3(_CAN);
    public static final TypeISOCountryCodeA3 CPV = new TypeISOCountryCodeA3(_CPV);
    public static final TypeISOCountryCodeA3 CYM = new TypeISOCountryCodeA3(_CYM);
    public static final TypeISOCountryCodeA3 CAF = new TypeISOCountryCodeA3(_CAF);
    public static final TypeISOCountryCodeA3 TCD = new TypeISOCountryCodeA3(_TCD);
    public static final TypeISOCountryCodeA3 CHL = new TypeISOCountryCodeA3(_CHL);
    public static final TypeISOCountryCodeA3 CHN = new TypeISOCountryCodeA3(_CHN);
    public static final TypeISOCountryCodeA3 CXR = new TypeISOCountryCodeA3(_CXR);
    public static final TypeISOCountryCodeA3 CCK = new TypeISOCountryCodeA3(_CCK);
    public static final TypeISOCountryCodeA3 COL = new TypeISOCountryCodeA3(_COL);
    public static final TypeISOCountryCodeA3 COM = new TypeISOCountryCodeA3(_COM);
    public static final TypeISOCountryCodeA3 COG = new TypeISOCountryCodeA3(_COG);
    public static final TypeISOCountryCodeA3 COD = new TypeISOCountryCodeA3(_COD);
    public static final TypeISOCountryCodeA3 COK = new TypeISOCountryCodeA3(_COK);
    public static final TypeISOCountryCodeA3 CRI = new TypeISOCountryCodeA3(_CRI);
    public static final TypeISOCountryCodeA3 CIV = new TypeISOCountryCodeA3(_CIV);
    public static final TypeISOCountryCodeA3 HRV = new TypeISOCountryCodeA3(_HRV);
    public static final TypeISOCountryCodeA3 CUB = new TypeISOCountryCodeA3(_CUB);
    public static final TypeISOCountryCodeA3 CYP = new TypeISOCountryCodeA3(_CYP);
    public static final TypeISOCountryCodeA3 CZE = new TypeISOCountryCodeA3(_CZE);
    public static final TypeISOCountryCodeA3 DNK = new TypeISOCountryCodeA3(_DNK);
    public static final TypeISOCountryCodeA3 DJI = new TypeISOCountryCodeA3(_DJI);
    public static final TypeISOCountryCodeA3 DMA = new TypeISOCountryCodeA3(_DMA);
    public static final TypeISOCountryCodeA3 DOM = new TypeISOCountryCodeA3(_DOM);
    public static final TypeISOCountryCodeA3 ECU = new TypeISOCountryCodeA3(_ECU);
    public static final TypeISOCountryCodeA3 EGY = new TypeISOCountryCodeA3(_EGY);
    public static final TypeISOCountryCodeA3 SLV = new TypeISOCountryCodeA3(_SLV);
    public static final TypeISOCountryCodeA3 GNQ = new TypeISOCountryCodeA3(_GNQ);
    public static final TypeISOCountryCodeA3 ERI = new TypeISOCountryCodeA3(_ERI);
    public static final TypeISOCountryCodeA3 EST = new TypeISOCountryCodeA3(_EST);
    public static final TypeISOCountryCodeA3 ETH = new TypeISOCountryCodeA3(_ETH);
    public static final TypeISOCountryCodeA3 FLK = new TypeISOCountryCodeA3(_FLK);
    public static final TypeISOCountryCodeA3 FRO = new TypeISOCountryCodeA3(_FRO);
    public static final TypeISOCountryCodeA3 FJI = new TypeISOCountryCodeA3(_FJI);
    public static final TypeISOCountryCodeA3 FIN = new TypeISOCountryCodeA3(_FIN);
    public static final TypeISOCountryCodeA3 FRA = new TypeISOCountryCodeA3(_FRA);
    public static final TypeISOCountryCodeA3 FXX = new TypeISOCountryCodeA3(_FXX);
    public static final TypeISOCountryCodeA3 GUF = new TypeISOCountryCodeA3(_GUF);
    public static final TypeISOCountryCodeA3 PYF = new TypeISOCountryCodeA3(_PYF);
    public static final TypeISOCountryCodeA3 ATF = new TypeISOCountryCodeA3(_ATF);
    public static final TypeISOCountryCodeA3 GAB = new TypeISOCountryCodeA3(_GAB);
    public static final TypeISOCountryCodeA3 GMB = new TypeISOCountryCodeA3(_GMB);
    public static final TypeISOCountryCodeA3 GEO = new TypeISOCountryCodeA3(_GEO);
    public static final TypeISOCountryCodeA3 DEU = new TypeISOCountryCodeA3(_DEU);
    public static final TypeISOCountryCodeA3 GHA = new TypeISOCountryCodeA3(_GHA);
    public static final TypeISOCountryCodeA3 GIB = new TypeISOCountryCodeA3(_GIB);
    public static final TypeISOCountryCodeA3 GRC = new TypeISOCountryCodeA3(_GRC);
    public static final TypeISOCountryCodeA3 GRL = new TypeISOCountryCodeA3(_GRL);
    public static final TypeISOCountryCodeA3 GRD = new TypeISOCountryCodeA3(_GRD);
    public static final TypeISOCountryCodeA3 GLP = new TypeISOCountryCodeA3(_GLP);
    public static final TypeISOCountryCodeA3 GUM = new TypeISOCountryCodeA3(_GUM);
    public static final TypeISOCountryCodeA3 GTM = new TypeISOCountryCodeA3(_GTM);
    public static final TypeISOCountryCodeA3 GGY = new TypeISOCountryCodeA3(_GGY);
    public static final TypeISOCountryCodeA3 GIN = new TypeISOCountryCodeA3(_GIN);
    public static final TypeISOCountryCodeA3 GNB = new TypeISOCountryCodeA3(_GNB);
    public static final TypeISOCountryCodeA3 GUY = new TypeISOCountryCodeA3(_GUY);
    public static final TypeISOCountryCodeA3 HTI = new TypeISOCountryCodeA3(_HTI);
    public static final TypeISOCountryCodeA3 HMD = new TypeISOCountryCodeA3(_HMD);
    public static final TypeISOCountryCodeA3 VAT = new TypeISOCountryCodeA3(_VAT);
    public static final TypeISOCountryCodeA3 HND = new TypeISOCountryCodeA3(_HND);
    public static final TypeISOCountryCodeA3 HKG = new TypeISOCountryCodeA3(_HKG);
    public static final TypeISOCountryCodeA3 HUN = new TypeISOCountryCodeA3(_HUN);
    public static final TypeISOCountryCodeA3 ISL = new TypeISOCountryCodeA3(_ISL);
    public static final TypeISOCountryCodeA3 IND = new TypeISOCountryCodeA3(_IND);
    public static final TypeISOCountryCodeA3 IDN = new TypeISOCountryCodeA3(_IDN);
    public static final TypeISOCountryCodeA3 IRN = new TypeISOCountryCodeA3(_IRN);
    public static final TypeISOCountryCodeA3 IRQ = new TypeISOCountryCodeA3(_IRQ);
    public static final TypeISOCountryCodeA3 IRL = new TypeISOCountryCodeA3(_IRL);
    public static final TypeISOCountryCodeA3 IMN = new TypeISOCountryCodeA3(_IMN);
    public static final TypeISOCountryCodeA3 ISR = new TypeISOCountryCodeA3(_ISR);
    public static final TypeISOCountryCodeA3 ITA = new TypeISOCountryCodeA3(_ITA);
    public static final TypeISOCountryCodeA3 JAM = new TypeISOCountryCodeA3(_JAM);
    public static final TypeISOCountryCodeA3 JPN = new TypeISOCountryCodeA3(_JPN);
    public static final TypeISOCountryCodeA3 JEY = new TypeISOCountryCodeA3(_JEY);
    public static final TypeISOCountryCodeA3 JOR = new TypeISOCountryCodeA3(_JOR);
    public static final TypeISOCountryCodeA3 KAZ = new TypeISOCountryCodeA3(_KAZ);
    public static final TypeISOCountryCodeA3 KEN = new TypeISOCountryCodeA3(_KEN);
    public static final TypeISOCountryCodeA3 KIR = new TypeISOCountryCodeA3(_KIR);
    public static final TypeISOCountryCodeA3 PRK = new TypeISOCountryCodeA3(_PRK);
    public static final TypeISOCountryCodeA3 KOR = new TypeISOCountryCodeA3(_KOR);
    public static final TypeISOCountryCodeA3 KWT = new TypeISOCountryCodeA3(_KWT);
    public static final TypeISOCountryCodeA3 KGZ = new TypeISOCountryCodeA3(_KGZ);
    public static final TypeISOCountryCodeA3 LAO = new TypeISOCountryCodeA3(_LAO);
    public static final TypeISOCountryCodeA3 LVA = new TypeISOCountryCodeA3(_LVA);
    public static final TypeISOCountryCodeA3 LBN = new TypeISOCountryCodeA3(_LBN);
    public static final TypeISOCountryCodeA3 LSO = new TypeISOCountryCodeA3(_LSO);
    public static final TypeISOCountryCodeA3 LBR = new TypeISOCountryCodeA3(_LBR);
    public static final TypeISOCountryCodeA3 LBY = new TypeISOCountryCodeA3(_LBY);
    public static final TypeISOCountryCodeA3 LIE = new TypeISOCountryCodeA3(_LIE);
    public static final TypeISOCountryCodeA3 LTU = new TypeISOCountryCodeA3(_LTU);
    public static final TypeISOCountryCodeA3 LUX = new TypeISOCountryCodeA3(_LUX);
    public static final TypeISOCountryCodeA3 MAC = new TypeISOCountryCodeA3(_MAC);
    public static final TypeISOCountryCodeA3 MKD = new TypeISOCountryCodeA3(_MKD);
    public static final TypeISOCountryCodeA3 MDG = new TypeISOCountryCodeA3(_MDG);
    public static final TypeISOCountryCodeA3 MWI = new TypeISOCountryCodeA3(_MWI);
    public static final TypeISOCountryCodeA3 MYS = new TypeISOCountryCodeA3(_MYS);
    public static final TypeISOCountryCodeA3 MDV = new TypeISOCountryCodeA3(_MDV);
    public static final TypeISOCountryCodeA3 MLI = new TypeISOCountryCodeA3(_MLI);
    public static final TypeISOCountryCodeA3 MLT = new TypeISOCountryCodeA3(_MLT);
    public static final TypeISOCountryCodeA3 MHL = new TypeISOCountryCodeA3(_MHL);
    public static final TypeISOCountryCodeA3 MTQ = new TypeISOCountryCodeA3(_MTQ);
    public static final TypeISOCountryCodeA3 MRT = new TypeISOCountryCodeA3(_MRT);
    public static final TypeISOCountryCodeA3 MUS = new TypeISOCountryCodeA3(_MUS);
    public static final TypeISOCountryCodeA3 MYT = new TypeISOCountryCodeA3(_MYT);
    public static final TypeISOCountryCodeA3 MEX = new TypeISOCountryCodeA3(_MEX);
    public static final TypeISOCountryCodeA3 FSM = new TypeISOCountryCodeA3(_FSM);
    public static final TypeISOCountryCodeA3 MDA = new TypeISOCountryCodeA3(_MDA);
    public static final TypeISOCountryCodeA3 MCO = new TypeISOCountryCodeA3(_MCO);
    public static final TypeISOCountryCodeA3 MNG = new TypeISOCountryCodeA3(_MNG);
    public static final TypeISOCountryCodeA3 MNE = new TypeISOCountryCodeA3(_MNE);
    public static final TypeISOCountryCodeA3 MSR = new TypeISOCountryCodeA3(_MSR);
    public static final TypeISOCountryCodeA3 MAR = new TypeISOCountryCodeA3(_MAR);
    public static final TypeISOCountryCodeA3 MOZ = new TypeISOCountryCodeA3(_MOZ);
    public static final TypeISOCountryCodeA3 MMR = new TypeISOCountryCodeA3(_MMR);
    public static final TypeISOCountryCodeA3 NAM = new TypeISOCountryCodeA3(_NAM);
    public static final TypeISOCountryCodeA3 NRU = new TypeISOCountryCodeA3(_NRU);
    public static final TypeISOCountryCodeA3 NPL = new TypeISOCountryCodeA3(_NPL);
    public static final TypeISOCountryCodeA3 NLD = new TypeISOCountryCodeA3(_NLD);
    public static final TypeISOCountryCodeA3 ANT = new TypeISOCountryCodeA3(_ANT);
    public static final TypeISOCountryCodeA3 NCL = new TypeISOCountryCodeA3(_NCL);
    public static final TypeISOCountryCodeA3 NZL = new TypeISOCountryCodeA3(_NZL);
    public static final TypeISOCountryCodeA3 NIC = new TypeISOCountryCodeA3(_NIC);
    public static final TypeISOCountryCodeA3 NER = new TypeISOCountryCodeA3(_NER);
    public static final TypeISOCountryCodeA3 NGA = new TypeISOCountryCodeA3(_NGA);
    public static final TypeISOCountryCodeA3 NIU = new TypeISOCountryCodeA3(_NIU);
    public static final TypeISOCountryCodeA3 NFK = new TypeISOCountryCodeA3(_NFK);
    public static final TypeISOCountryCodeA3 MNP = new TypeISOCountryCodeA3(_MNP);
    public static final TypeISOCountryCodeA3 NOR = new TypeISOCountryCodeA3(_NOR);
    public static final TypeISOCountryCodeA3 OMN = new TypeISOCountryCodeA3(_OMN);
    public static final TypeISOCountryCodeA3 PAK = new TypeISOCountryCodeA3(_PAK);
    public static final TypeISOCountryCodeA3 PLW = new TypeISOCountryCodeA3(_PLW);
    public static final TypeISOCountryCodeA3 PSE = new TypeISOCountryCodeA3(_PSE);
    public static final TypeISOCountryCodeA3 PAN = new TypeISOCountryCodeA3(_PAN);
    public static final TypeISOCountryCodeA3 PNG = new TypeISOCountryCodeA3(_PNG);
    public static final TypeISOCountryCodeA3 PRY = new TypeISOCountryCodeA3(_PRY);
    public static final TypeISOCountryCodeA3 PER = new TypeISOCountryCodeA3(_PER);
    public static final TypeISOCountryCodeA3 PHL = new TypeISOCountryCodeA3(_PHL);
    public static final TypeISOCountryCodeA3 PCN = new TypeISOCountryCodeA3(_PCN);
    public static final TypeISOCountryCodeA3 POL = new TypeISOCountryCodeA3(_POL);
    public static final TypeISOCountryCodeA3 PRT = new TypeISOCountryCodeA3(_PRT);
    public static final TypeISOCountryCodeA3 PRI = new TypeISOCountryCodeA3(_PRI);
    public static final TypeISOCountryCodeA3 QAT = new TypeISOCountryCodeA3(_QAT);
    public static final TypeISOCountryCodeA3 REU = new TypeISOCountryCodeA3(_REU);
    public static final TypeISOCountryCodeA3 ROU = new TypeISOCountryCodeA3(_ROU);
    public static final TypeISOCountryCodeA3 RUS = new TypeISOCountryCodeA3(_RUS);
    public static final TypeISOCountryCodeA3 RWA = new TypeISOCountryCodeA3(_RWA);
    public static final TypeISOCountryCodeA3 SHN = new TypeISOCountryCodeA3(_SHN);
    public static final TypeISOCountryCodeA3 KNA = new TypeISOCountryCodeA3(_KNA);
    public static final TypeISOCountryCodeA3 LCA = new TypeISOCountryCodeA3(_LCA);
    public static final TypeISOCountryCodeA3 SPM = new TypeISOCountryCodeA3(_SPM);
    public static final TypeISOCountryCodeA3 VCT = new TypeISOCountryCodeA3(_VCT);
    public static final TypeISOCountryCodeA3 WSM = new TypeISOCountryCodeA3(_WSM);
    public static final TypeISOCountryCodeA3 SMR = new TypeISOCountryCodeA3(_SMR);
    public static final TypeISOCountryCodeA3 STP = new TypeISOCountryCodeA3(_STP);
    public static final TypeISOCountryCodeA3 SAU = new TypeISOCountryCodeA3(_SAU);
    public static final TypeISOCountryCodeA3 SEN = new TypeISOCountryCodeA3(_SEN);
    public static final TypeISOCountryCodeA3 SRB = new TypeISOCountryCodeA3(_SRB);
    public static final TypeISOCountryCodeA3 SCG = new TypeISOCountryCodeA3(_SCG);
    public static final TypeISOCountryCodeA3 SYC = new TypeISOCountryCodeA3(_SYC);
    public static final TypeISOCountryCodeA3 SLE = new TypeISOCountryCodeA3(_SLE);
    public static final TypeISOCountryCodeA3 SGP = new TypeISOCountryCodeA3(_SGP);
    public static final TypeISOCountryCodeA3 SVK = new TypeISOCountryCodeA3(_SVK);
    public static final TypeISOCountryCodeA3 SVN = new TypeISOCountryCodeA3(_SVN);
    public static final TypeISOCountryCodeA3 SLB = new TypeISOCountryCodeA3(_SLB);
    public static final TypeISOCountryCodeA3 SOM = new TypeISOCountryCodeA3(_SOM);
    public static final TypeISOCountryCodeA3 ZAF = new TypeISOCountryCodeA3(_ZAF);
    public static final TypeISOCountryCodeA3 SGS = new TypeISOCountryCodeA3(_SGS);
    public static final TypeISOCountryCodeA3 ESP = new TypeISOCountryCodeA3(_ESP);
    public static final TypeISOCountryCodeA3 LKA = new TypeISOCountryCodeA3(_LKA);
    public static final TypeISOCountryCodeA3 SDN = new TypeISOCountryCodeA3(_SDN);
    public static final TypeISOCountryCodeA3 SUR = new TypeISOCountryCodeA3(_SUR);
    public static final TypeISOCountryCodeA3 SJM = new TypeISOCountryCodeA3(_SJM);
    public static final TypeISOCountryCodeA3 SWZ = new TypeISOCountryCodeA3(_SWZ);
    public static final TypeISOCountryCodeA3 SWE = new TypeISOCountryCodeA3(_SWE);
    public static final TypeISOCountryCodeA3 CHE = new TypeISOCountryCodeA3(_CHE);
    public static final TypeISOCountryCodeA3 SYR = new TypeISOCountryCodeA3(_SYR);
    public static final TypeISOCountryCodeA3 TWN = new TypeISOCountryCodeA3(_TWN);
    public static final TypeISOCountryCodeA3 TJK = new TypeISOCountryCodeA3(_TJK);
    public static final TypeISOCountryCodeA3 TZA = new TypeISOCountryCodeA3(_TZA);
    public static final TypeISOCountryCodeA3 THA = new TypeISOCountryCodeA3(_THA);
    public static final TypeISOCountryCodeA3 TLS = new TypeISOCountryCodeA3(_TLS);
    public static final TypeISOCountryCodeA3 TGO = new TypeISOCountryCodeA3(_TGO);
    public static final TypeISOCountryCodeA3 TKL = new TypeISOCountryCodeA3(_TKL);
    public static final TypeISOCountryCodeA3 TMP = new TypeISOCountryCodeA3(_TMP);
    public static final TypeISOCountryCodeA3 TON = new TypeISOCountryCodeA3(_TON);
    public static final TypeISOCountryCodeA3 TTO = new TypeISOCountryCodeA3(_TTO);
    public static final TypeISOCountryCodeA3 TUN = new TypeISOCountryCodeA3(_TUN);
    public static final TypeISOCountryCodeA3 TUR = new TypeISOCountryCodeA3(_TUR);
    public static final TypeISOCountryCodeA3 TKM = new TypeISOCountryCodeA3(_TKM);
    public static final TypeISOCountryCodeA3 TCA = new TypeISOCountryCodeA3(_TCA);
    public static final TypeISOCountryCodeA3 TUV = new TypeISOCountryCodeA3(_TUV);
    public static final TypeISOCountryCodeA3 UGA = new TypeISOCountryCodeA3(_UGA);
    public static final TypeISOCountryCodeA3 UKR = new TypeISOCountryCodeA3(_UKR);
    public static final TypeISOCountryCodeA3 ARE = new TypeISOCountryCodeA3(_ARE);
    public static final TypeISOCountryCodeA3 GBR = new TypeISOCountryCodeA3(_GBR);
    public static final TypeISOCountryCodeA3 USA = new TypeISOCountryCodeA3(_USA);
    public static final TypeISOCountryCodeA3 UMI = new TypeISOCountryCodeA3(_UMI);
    public static final TypeISOCountryCodeA3 URY = new TypeISOCountryCodeA3(_URY);
    public static final TypeISOCountryCodeA3 UZB = new TypeISOCountryCodeA3(_UZB);
    public static final TypeISOCountryCodeA3 VUT = new TypeISOCountryCodeA3(_VUT);
    public static final TypeISOCountryCodeA3 VEN = new TypeISOCountryCodeA3(_VEN);
    public static final TypeISOCountryCodeA3 VNM = new TypeISOCountryCodeA3(_VNM);
    public static final TypeISOCountryCodeA3 VGB = new TypeISOCountryCodeA3(_VGB);
    public static final TypeISOCountryCodeA3 VIR = new TypeISOCountryCodeA3(_VIR);
    public static final TypeISOCountryCodeA3 WLF = new TypeISOCountryCodeA3(_WLF);
    public static final TypeISOCountryCodeA3 ESH = new TypeISOCountryCodeA3(_ESH);
    public static final TypeISOCountryCodeA3 YEM = new TypeISOCountryCodeA3(_YEM);
    public static final TypeISOCountryCodeA3 YUG = new TypeISOCountryCodeA3(_YUG);
    public static final TypeISOCountryCodeA3 ZMB = new TypeISOCountryCodeA3(_ZMB);
    public static final TypeISOCountryCodeA3 ZWE = new TypeISOCountryCodeA3(_ZWE);
    public java.lang.String getValue() { return _value_;}
    public static TypeISOCountryCodeA3 fromValue(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        TypeISOCountryCodeA3 enumeration = (TypeISOCountryCodeA3)
            _table_.get(value);
        if (enumeration==null) throw new java.lang.IllegalArgumentException();
        return enumeration;
    }
    public static TypeISOCountryCodeA3 fromString(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        return fromValue(value);
    }
    public boolean equals(java.lang.Object obj) {return (obj == this);}
    public int hashCode() { return toString().hashCode();}
    public java.lang.String toString() { return _value_;}
    public java.lang.Object readResolve() throws java.io.ObjectStreamException { return fromValue(_value_);}
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumSerializer(
            _javaType, _xmlType);
    }
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumDeserializer(
            _javaType, _xmlType);
    }
    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(TypeISOCountryCodeA3.class);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation", "TypeISOCountryCodeA3"));
    }
    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

}
