/**
 * BankcardData.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.ipcommerce.schemas.CWS.v2_0.DataServices.TMS;


/**
 * <summary>
 *             Transaction information specific to Bankcard transactions.
 * Conditional, included if the query includes Bankcard transactions.
 * </summary>
 */
public class BankcardData  implements java.io.Serializable {
    /* <summary>
     *             Collection of elements that indicate the result of AVS
     * returned by the Service Provider. Optional.
     *             </summary> */
    private com.ipcommerce.schemas.CWS.v2_0.Transactions.Bankcard.AVSResult AVSResult;

    /* <summary>
     *             Response code returned by the card issuer indicating the
     * result of Card Verification (CVV2/CVC2/CID) returned by the Service
     * Provider. Optional.
     *             </summary> */
    private com.ipcommerce.schemas.CWS.v2_0.Transactions.CVResult CVResult;

    /* <summary>
     *             Type of card used in the transaction. Expected.
     *             </summary> */
    private com.ipcommerce.schemas.CWS.v2_0.Transactions.Bankcard.TypeCardType cardType;

    /* <summary>
     *             The cardholder's PAN in masked format. Expected.
     *             </summary> */
    private java.lang.String maskedPAN;

    /* <summary>
     *              The order id generated by CWS. This value is often used
     * by Service Providers for transaction correlation. Expected.
     *             </summary> */
    private java.lang.String orderId;

    public BankcardData() {
    }

    public BankcardData(
           com.ipcommerce.schemas.CWS.v2_0.Transactions.Bankcard.AVSResult AVSResult,
           com.ipcommerce.schemas.CWS.v2_0.Transactions.CVResult CVResult,
           com.ipcommerce.schemas.CWS.v2_0.Transactions.Bankcard.TypeCardType cardType,
           java.lang.String maskedPAN,
           java.lang.String orderId) {
           this.AVSResult = AVSResult;
           this.CVResult = CVResult;
           this.cardType = cardType;
           this.maskedPAN = maskedPAN;
           this.orderId = orderId;
    }


    /**
     * Gets the AVSResult value for this BankcardData.
     * 
     * @return AVSResult   * <summary>
     *             Collection of elements that indicate the result of AVS
     * returned by the Service Provider. Optional.
     *             </summary>
     */
    public com.ipcommerce.schemas.CWS.v2_0.Transactions.Bankcard.AVSResult getAVSResult() {
        return AVSResult;
    }


    /**
     * Sets the AVSResult value for this BankcardData.
     * 
     * @param AVSResult   * <summary>
     *             Collection of elements that indicate the result of AVS
     * returned by the Service Provider. Optional.
     *             </summary>
     */
    public void setAVSResult(com.ipcommerce.schemas.CWS.v2_0.Transactions.Bankcard.AVSResult AVSResult) {
        this.AVSResult = AVSResult;
    }


    /**
     * Gets the CVResult value for this BankcardData.
     * 
     * @return CVResult   * <summary>
     *             Response code returned by the card issuer indicating the
     * result of Card Verification (CVV2/CVC2/CID) returned by the Service
     * Provider. Optional.
     *             </summary>
     */
    public com.ipcommerce.schemas.CWS.v2_0.Transactions.CVResult getCVResult() {
        return CVResult;
    }


    /**
     * Sets the CVResult value for this BankcardData.
     * 
     * @param CVResult   * <summary>
     *             Response code returned by the card issuer indicating the
     * result of Card Verification (CVV2/CVC2/CID) returned by the Service
     * Provider. Optional.
     *             </summary>
     */
    public void setCVResult(com.ipcommerce.schemas.CWS.v2_0.Transactions.CVResult CVResult) {
        this.CVResult = CVResult;
    }


    /**
     * Gets the cardType value for this BankcardData.
     * 
     * @return cardType   * <summary>
     *             Type of card used in the transaction. Expected.
     *             </summary>
     */
    public com.ipcommerce.schemas.CWS.v2_0.Transactions.Bankcard.TypeCardType getCardType() {
        return cardType;
    }


    /**
     * Sets the cardType value for this BankcardData.
     * 
     * @param cardType   * <summary>
     *             Type of card used in the transaction. Expected.
     *             </summary>
     */
    public void setCardType(com.ipcommerce.schemas.CWS.v2_0.Transactions.Bankcard.TypeCardType cardType) {
        this.cardType = cardType;
    }


    /**
     * Gets the maskedPAN value for this BankcardData.
     * 
     * @return maskedPAN   * <summary>
     *             The cardholder's PAN in masked format. Expected.
     *             </summary>
     */
    public java.lang.String getMaskedPAN() {
        return maskedPAN;
    }


    /**
     * Sets the maskedPAN value for this BankcardData.
     * 
     * @param maskedPAN   * <summary>
     *             The cardholder's PAN in masked format. Expected.
     *             </summary>
     */
    public void setMaskedPAN(java.lang.String maskedPAN) {
        this.maskedPAN = maskedPAN;
    }


    /**
     * Gets the orderId value for this BankcardData.
     * 
     * @return orderId   * <summary>
     *              The order id generated by CWS. This value is often used
     * by Service Providers for transaction correlation. Expected.
     *             </summary>
     */
    public java.lang.String getOrderId() {
        return orderId;
    }


    /**
     * Sets the orderId value for this BankcardData.
     * 
     * @param orderId   * <summary>
     *              The order id generated by CWS. This value is often used
     * by Service Providers for transaction correlation. Expected.
     *             </summary>
     */
    public void setOrderId(java.lang.String orderId) {
        this.orderId = orderId;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof BankcardData)) return false;
        BankcardData other = (BankcardData) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.AVSResult==null && other.getAVSResult()==null) || 
             (this.AVSResult!=null &&
              this.AVSResult.equals(other.getAVSResult()))) &&
            ((this.CVResult==null && other.getCVResult()==null) || 
             (this.CVResult!=null &&
              this.CVResult.equals(other.getCVResult()))) &&
            ((this.cardType==null && other.getCardType()==null) || 
             (this.cardType!=null &&
              this.cardType.equals(other.getCardType()))) &&
            ((this.maskedPAN==null && other.getMaskedPAN()==null) || 
             (this.maskedPAN!=null &&
              this.maskedPAN.equals(other.getMaskedPAN()))) &&
            ((this.orderId==null && other.getOrderId()==null) || 
             (this.orderId!=null &&
              this.orderId.equals(other.getOrderId())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getAVSResult() != null) {
            _hashCode += getAVSResult().hashCode();
        }
        if (getCVResult() != null) {
            _hashCode += getCVResult().hashCode();
        }
        if (getCardType() != null) {
            _hashCode += getCardType().hashCode();
        }
        if (getMaskedPAN() != null) {
            _hashCode += getMaskedPAN().hashCode();
        }
        if (getOrderId() != null) {
            _hashCode += getOrderId().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(BankcardData.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "BankcardData"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("AVSResult");
        elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "AVSResult"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Bankcard", "AVSResult"));
        elemField.setMinOccurs(0);
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("CVResult");
        elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "CVResult"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/Transactions", "CVResult"));
        elemField.setMinOccurs(0);
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cardType");
        elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "CardType"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Bankcard", "TypeCardType"));
        elemField.setMinOccurs(0);
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("maskedPAN");
        elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "MaskedPAN"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setMinOccurs(0);
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("orderId");
        elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "OrderId"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setMinOccurs(0);
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
