/**
 * StoredValueData.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.ipcommerce.schemas.CWS.v2_0.DataServices.TMS;


/**
 * <summary>
 *             Transaction information specific to Stored Value transactions.
 * Conditional, included if the query includes Bankcard transactions.
 * </summary>
 */
public class StoredValueData  implements java.io.Serializable {
    /* <summary>
     *             Response code returned by the card issuer indicating the
     * result of Card Verification (CVV2/CVC2/CID) returned by the Service
     * Provider. Optional.
     *             </summary> */
    private com.ipcommerce.schemas.CWS.v2_0.Transactions.CVResult CVResult;

    /* <summary>
     *             Specifies the gift card restriction value assigned to
     * a specific card. Optional.
     *             </summary> */
    private java.lang.String cardRestrictionValue;

    /* <summary>
     *             Indicates the status of the card if one is present. Optional.
     * </summary> */
    private com.ipcommerce.schemas.CWS.v2_0.Transactions.StoredValue.CardStatus cardStatus;

    /* <summary>
     *             The account balance after the transaction. Required.
     *             </summary> */
    private java.math.BigDecimal newBalance;

    /* <summary>
     *              The order id generated by CWS. This value is often used
     * by Service Providers for transaction correlation. Expected.
     *             </summary> */
    private java.lang.String orderId;

    /* <summary>
     *             The account balance prior to the transaction. Optional.
     * </summary> */
    private java.math.BigDecimal previousBalance;

    public StoredValueData() {
    }

    public StoredValueData(
           com.ipcommerce.schemas.CWS.v2_0.Transactions.CVResult CVResult,
           java.lang.String cardRestrictionValue,
           com.ipcommerce.schemas.CWS.v2_0.Transactions.StoredValue.CardStatus cardStatus,
           java.math.BigDecimal newBalance,
           java.lang.String orderId,
           java.math.BigDecimal previousBalance) {
           this.CVResult = CVResult;
           this.cardRestrictionValue = cardRestrictionValue;
           this.cardStatus = cardStatus;
           this.newBalance = newBalance;
           this.orderId = orderId;
           this.previousBalance = previousBalance;
    }


    /**
     * Gets the CVResult value for this StoredValueData.
     * 
     * @return CVResult   * <summary>
     *             Response code returned by the card issuer indicating the
     * result of Card Verification (CVV2/CVC2/CID) returned by the Service
     * Provider. Optional.
     *             </summary>
     */
    public com.ipcommerce.schemas.CWS.v2_0.Transactions.CVResult getCVResult() {
        return CVResult;
    }


    /**
     * Sets the CVResult value for this StoredValueData.
     * 
     * @param CVResult   * <summary>
     *             Response code returned by the card issuer indicating the
     * result of Card Verification (CVV2/CVC2/CID) returned by the Service
     * Provider. Optional.
     *             </summary>
     */
    public void setCVResult(com.ipcommerce.schemas.CWS.v2_0.Transactions.CVResult CVResult) {
        this.CVResult = CVResult;
    }


    /**
     * Gets the cardRestrictionValue value for this StoredValueData.
     * 
     * @return cardRestrictionValue   * <summary>
     *             Specifies the gift card restriction value assigned to
     * a specific card. Optional.
     *             </summary>
     */
    public java.lang.String getCardRestrictionValue() {
        return cardRestrictionValue;
    }


    /**
     * Sets the cardRestrictionValue value for this StoredValueData.
     * 
     * @param cardRestrictionValue   * <summary>
     *             Specifies the gift card restriction value assigned to
     * a specific card. Optional.
     *             </summary>
     */
    public void setCardRestrictionValue(java.lang.String cardRestrictionValue) {
        this.cardRestrictionValue = cardRestrictionValue;
    }


    /**
     * Gets the cardStatus value for this StoredValueData.
     * 
     * @return cardStatus   * <summary>
     *             Indicates the status of the card if one is present. Optional.
     * </summary>
     */
    public com.ipcommerce.schemas.CWS.v2_0.Transactions.StoredValue.CardStatus getCardStatus() {
        return cardStatus;
    }


    /**
     * Sets the cardStatus value for this StoredValueData.
     * 
     * @param cardStatus   * <summary>
     *             Indicates the status of the card if one is present. Optional.
     * </summary>
     */
    public void setCardStatus(com.ipcommerce.schemas.CWS.v2_0.Transactions.StoredValue.CardStatus cardStatus) {
        this.cardStatus = cardStatus;
    }


    /**
     * Gets the newBalance value for this StoredValueData.
     * 
     * @return newBalance   * <summary>
     *             The account balance after the transaction. Required.
     *             </summary>
     */
    public java.math.BigDecimal getNewBalance() {
        return newBalance;
    }


    /**
     * Sets the newBalance value for this StoredValueData.
     * 
     * @param newBalance   * <summary>
     *             The account balance after the transaction. Required.
     *             </summary>
     */
    public void setNewBalance(java.math.BigDecimal newBalance) {
        this.newBalance = newBalance;
    }


    /**
     * Gets the orderId value for this StoredValueData.
     * 
     * @return orderId   * <summary>
     *              The order id generated by CWS. This value is often used
     * by Service Providers for transaction correlation. Expected.
     *             </summary>
     */
    public java.lang.String getOrderId() {
        return orderId;
    }


    /**
     * Sets the orderId value for this StoredValueData.
     * 
     * @param orderId   * <summary>
     *              The order id generated by CWS. This value is often used
     * by Service Providers for transaction correlation. Expected.
     *             </summary>
     */
    public void setOrderId(java.lang.String orderId) {
        this.orderId = orderId;
    }


    /**
     * Gets the previousBalance value for this StoredValueData.
     * 
     * @return previousBalance   * <summary>
     *             The account balance prior to the transaction. Optional.
     * </summary>
     */
    public java.math.BigDecimal getPreviousBalance() {
        return previousBalance;
    }


    /**
     * Sets the previousBalance value for this StoredValueData.
     * 
     * @param previousBalance   * <summary>
     *             The account balance prior to the transaction. Optional.
     * </summary>
     */
    public void setPreviousBalance(java.math.BigDecimal previousBalance) {
        this.previousBalance = previousBalance;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof StoredValueData)) return false;
        StoredValueData other = (StoredValueData) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.CVResult==null && other.getCVResult()==null) || 
             (this.CVResult!=null &&
              this.CVResult.equals(other.getCVResult()))) &&
            ((this.cardRestrictionValue==null && other.getCardRestrictionValue()==null) || 
             (this.cardRestrictionValue!=null &&
              this.cardRestrictionValue.equals(other.getCardRestrictionValue()))) &&
            ((this.cardStatus==null && other.getCardStatus()==null) || 
             (this.cardStatus!=null &&
              this.cardStatus.equals(other.getCardStatus()))) &&
            ((this.newBalance==null && other.getNewBalance()==null) || 
             (this.newBalance!=null &&
              this.newBalance.equals(other.getNewBalance()))) &&
            ((this.orderId==null && other.getOrderId()==null) || 
             (this.orderId!=null &&
              this.orderId.equals(other.getOrderId()))) &&
            ((this.previousBalance==null && other.getPreviousBalance()==null) || 
             (this.previousBalance!=null &&
              this.previousBalance.equals(other.getPreviousBalance())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCVResult() != null) {
            _hashCode += getCVResult().hashCode();
        }
        if (getCardRestrictionValue() != null) {
            _hashCode += getCardRestrictionValue().hashCode();
        }
        if (getCardStatus() != null) {
            _hashCode += getCardStatus().hashCode();
        }
        if (getNewBalance() != null) {
            _hashCode += getNewBalance().hashCode();
        }
        if (getOrderId() != null) {
            _hashCode += getOrderId().hashCode();
        }
        if (getPreviousBalance() != null) {
            _hashCode += getPreviousBalance().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(StoredValueData.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "StoredValueData"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("CVResult");
        elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "CVResult"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/Transactions", "CVResult"));
        elemField.setMinOccurs(0);
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cardRestrictionValue");
        elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "CardRestrictionValue"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setMinOccurs(0);
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cardStatus");
        elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "CardStatus"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/Transactions/StoredValue", "CardStatus"));
        elemField.setMinOccurs(0);
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("newBalance");
        elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "NewBalance"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "decimal"));
        elemField.setMinOccurs(0);
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("orderId");
        elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "OrderId"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setMinOccurs(0);
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("previousBalance");
        elemField.setXmlName(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", "PreviousBalance"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "decimal"));
        elemField.setMinOccurs(0);
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
