/**
 * TypeUnitOfMeasure.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.ipcommerce.schemas.CWS.v2_0.Transactions.Bankcard;

public class TypeUnitOfMeasure implements java.io.Serializable {
    private java.lang.String _value_;
    private static java.util.HashMap _table_ = new java.util.HashMap();

    // Constructor
    protected TypeUnitOfMeasure(java.lang.String value) {
        _value_ = value;
        _table_.put(_value_,this);
    }

    public static final java.lang.String _NotSet = "NotSet";
    public static final java.lang.String _Acre = "Acre";
    public static final java.lang.String _AmpereHour = "AmpereHour";
    public static final java.lang.String _Ampere = "Ampere";
    public static final java.lang.String _Year = "Year";
    public static final java.lang.String _TroyOunceOrApothecariesOunce = "TroyOunceOrApothecariesOunce";
    public static final java.lang.String _Are = "Are";
    public static final java.lang.String _AlcoholicStrengthByMass = "AlcoholicStrengthByMass";
    public static final java.lang.String _AlcoholicStrengthByVolume = "AlcoholicStrengthByVolume";
    public static final java.lang.String _StandardAtmosphere = "StandardAtmosphere";
    public static final java.lang.String _TechnicalAtmosphere = "TechnicalAtmosphere";
    public static final java.lang.String _Bar = "Bar";
    public static final java.lang.String _BoardFoot = "BoardFoot";
    public static final java.lang.String _BrakeHorsePower = "BrakeHorsePower";
    public static final java.lang.String _BillionEURTrillionUS = "BillionEURTrillionUS";
    public static final java.lang.String _DryBarrelUS = "DryBarrelUS";
    public static final java.lang.String _BarrelUSPetroleumEtc = "BarrelUSPetroleumEtc";
    public static final java.lang.String _Becquerel = "Becquerel";
    public static final java.lang.String _BritishThermalUnit = "BritishThermalUnit";
    public static final java.lang.String _BushelUS = "BushelUS";
    public static final java.lang.String _BushelUK = "BushelUK";
    public static final java.lang.String _CarryingCapacityInMetricTon = "CarryingCapacityInMetricTon";
    public static final java.lang.String _Candela = "Candela";
    public static final java.lang.String _DegreeCelsius = "DegreeCelsius";
    public static final java.lang.String _Hundred = "Hundred";
    public static final java.lang.String _Centigram = "Centigram";
    public static final java.lang.String _CoulombPerKilogram = "CoulombPerKilogram";
    public static final java.lang.String _HundredLeave = "HundredLeave";
    public static final java.lang.String _Centilitre = "Centilitre";
    public static final java.lang.String _Centiliter = "Centiliter";
    public static final java.lang.String _SquareCentimetre = "SquareCentimetre";
    public static final java.lang.String _SquareCentimeter = "SquareCentimeter";
    public static final java.lang.String _CubicCentimetre = "CubicCentimetre";
    public static final java.lang.String _CubicCentimeter = "CubicCentimeter";
    public static final java.lang.String _Centimetre = "Centimetre";
    public static final java.lang.String _Centimeter = "Centimeter";
    public static final java.lang.String _HundredPack = "HundredPack";
    public static final java.lang.String _CentalUK = "CentalUK";
    public static final java.lang.String _Coulomb = "Coulomb";
    public static final java.lang.String _MetricCarat = "MetricCarat";
    public static final java.lang.String _Curie = "Curie";
    public static final java.lang.String _HundredPoundsCWTHundredWeightUS = "HundredPoundsCWTHundredWeightUS";
    public static final java.lang.String _HundredWeightUK = "HundredWeightUK";
    public static final java.lang.String _Decare = "Decare";
    public static final java.lang.String _TenDay = "TenDay";
    public static final java.lang.String _Day = "Day";
    public static final java.lang.String _Decade = "Decade";
    public static final java.lang.String _Decilitre = "Decilitre";
    public static final java.lang.String _Deciliter = "Deciliter";
    public static final java.lang.String _SquareDecimetre = "SquareDecimetre";
    public static final java.lang.String _SquareDecimeter = "SquareDecimeter";
    public static final java.lang.String _CubicDecimetre = "CubicDecimetre";
    public static final java.lang.String _CubicDecimeter = "CubicDecimeter";
    public static final java.lang.String _Decimetre = "Decimetre";
    public static final java.lang.String _Decimeter = "Decimeter";
    public static final java.lang.String _DozenPiece = "DozenPiece";
    public static final java.lang.String _DozenPair = "DozenPair";
    public static final java.lang.String _DisplacementTonnage = "DisplacementTonnage";
    public static final java.lang.String _DramUS = "DramUS";
    public static final java.lang.String _DramUK = "DramUK";
    public static final java.lang.String _DozenRoll = "DozenRoll";
    public static final java.lang.String _DrachmUK = "DrachmUK";
    public static final java.lang.String _DecitonneCentnerMetric100KgQuintalMetric100Kg = "DecitonneCentnerMetric100KgQuintalMetric100Kg";
    public static final java.lang.String _Pennyweight = "Pennyweight";
    public static final java.lang.String _Dozen = "Dozen";
    public static final java.lang.String _DozenPack = "DozenPack";
    public static final java.lang.String _DegreeFahrenheit = "DegreeFahrenheit";
    public static final java.lang.String _Farad = "Farad";
    public static final java.lang.String _Foot = "Foot";
    public static final java.lang.String _SquareFoot = "SquareFoot";
    public static final java.lang.String _CubicFoot = "CubicFoot";
    public static final java.lang.String _Gigabecquerel = "Gigabecquerel";
    public static final java.lang.String _GramOfFissileIsotope = "GramOfFissileIsotope";
    public static final java.lang.String _GreatGross = "GreatGross";
    public static final java.lang.String _GillUS = "GillUS";
    public static final java.lang.String _GillUK = "GillUK";
    public static final java.lang.String _DryGallonUS = "DryGallonUS";
    public static final java.lang.String _GallonUK = "GallonUK";
    public static final java.lang.String _GallonUS = "GallonUS";
    public static final java.lang.String _Gram = "Gram";
    public static final java.lang.String _Grain = "Grain";
    public static final java.lang.String _Gross = "Gross";
    public static final java.lang.String _GrossRegisterTon = "GrossRegisterTon";
    public static final java.lang.String _GigawattHour = "GigawattHour";
    public static final java.lang.String _Hectare = "Hectare";
    public static final java.lang.String _Hectobar = "Hectobar";
    public static final java.lang.String _HundredBox = "HundredBox";
    public static final java.lang.String _Hectogram = "Hectogram";
    public static final java.lang.String _HundredInternationalUnit = "HundredInternationalUnit";
    public static final java.lang.String _Hectolitre = "Hectolitre";
    public static final java.lang.String _Hectoliter = "Hectoliter";
    public static final java.lang.String _MillionCubicMetre = "MillionCubicMetre";
    public static final java.lang.String _MillionCubicMeter = "MillionCubicMeter";
    public static final java.lang.String _Hectometre = "Hectometre";
    public static final java.lang.String _Hectometer = "Hectometer";
    public static final java.lang.String _HectolitreOfPureAlcohol = "HectolitreOfPureAlcohol";
    public static final java.lang.String _HectoliterOfPureAlcohol = "HectoliterOfPureAlcohol";
    public static final java.lang.String _Hertz = "Hertz";
    public static final java.lang.String _Hour = "Hour";
    public static final java.lang.String _Inch = "Inch";
    public static final java.lang.String _SquareInch = "SquareInch";
    public static final java.lang.String _CubicInch = "CubicInch";
    public static final java.lang.String _Joule = "Joule";
    public static final java.lang.String _Kilobar = "Kilobar";
    public static final java.lang.String _Kelvin = "Kelvin";
    public static final java.lang.String _Kilogram = "Kilogram";
    public static final java.lang.String _KilogramPerSecond = "KilogramPerSecond";
    public static final java.lang.String _Kilohertz = "Kilohertz";
    public static final java.lang.String _Kilojoule = "Kilojoule";
    public static final java.lang.String _KilometrePerHour = "KilometrePerHour";
    public static final java.lang.String _KilometerPerHour = "KilometerPerHour";
    public static final java.lang.String _SquareKilometre = "SquareKilometre";
    public static final java.lang.String _SquareKilometer = "SquareKilometer";
    public static final java.lang.String _KilogramPerCubicMetre = "KilogramPerCubicMetre";
    public static final java.lang.String _KilogramPerCubicMeter = "KilogramPerCubicMeter";
    public static final java.lang.String _Kilometre = "Kilometre";
    public static final java.lang.String _Kilometer = "Kilometer";
    public static final java.lang.String _KilogramOfNitrogen = "KilogramOfNitrogen";
    public static final java.lang.String _KilogramNamedSubstance = "KilogramNamedSubstance";
    public static final java.lang.String _Knot = "Knot";
    public static final java.lang.String _Kilopascal = "Kilopascal";
    public static final java.lang.String _KilogramOfPotassiumHydroxideCausticPotash = "KilogramOfPotassiumHydroxideCausticPotash";
    public static final java.lang.String _KilogramOfPotassiumOxide = "KilogramOfPotassiumOxide";
    public static final java.lang.String _KilogramOfPhosphorusPentoxidePhosphoricAnhydride = "KilogramOfPhosphorusPentoxidePhosphoricAnhydride";
    public static final java.lang.String _KilogramOfSubstance90PercentDry = "KilogramOfSubstance90PercentDry";
    public static final java.lang.String _KilogramOfSodiumHydroxideCausticSoda = "KilogramOfSodiumHydroxideCausticSoda";
    public static final java.lang.String _Kilotonne = "Kilotonne";
    public static final java.lang.String _KilogramOfUranium = "KilogramOfUranium";
    public static final java.lang.String _KilovoltAmpere = "KilovoltAmpere";
    public static final java.lang.String _Kilovar = "Kilovar";
    public static final java.lang.String _Kilovolt = "Kilovolt";
    public static final java.lang.String _KilowattHour = "KilowattHour";
    public static final java.lang.String _Kilowatt = "Kilowatt";
    public static final java.lang.String _Pound = "Pound";
    public static final java.lang.String _TroyPoundUS = "TroyPoundUS";
    public static final java.lang.String _Leaf = "Leaf";
    public static final java.lang.String _LitreOfPureAlcohol = "LitreOfPureAlcohol";
    public static final java.lang.String _LiterOfPureAlcohol = "LiterOfPureAlcohol";
    public static final java.lang.String _TonUKorLongTonUS = "TonUKorLongTonUS";
    public static final java.lang.String _Litre = "Litre";
    public static final java.lang.String _Liter = "Liter";
    public static final java.lang.String _Lumen = "Lumen";
    public static final java.lang.String _Lux = "Lux";
    public static final java.lang.String _MegaLitre = "MegaLitre";
    public static final java.lang.String _MegaLiter = "MegaLiter";
    public static final java.lang.String _Megametre = "Megametre";
    public static final java.lang.String _Megameter = "Megameter";
    public static final java.lang.String _Megawatt = "Megawatt";
    public static final java.lang.String _ThousandStandardBrickEquivalent = "ThousandStandardBrickEquivalent";
    public static final java.lang.String _ThousandBoardFeet = "ThousandBoardFeet";
    public static final java.lang.String _Millibar = "Millibar";
    public static final java.lang.String _Millicurie = "Millicurie";
    public static final java.lang.String _Milligram = "Milligram";
    public static final java.lang.String _Megahertz = "Megahertz";
    public static final java.lang.String _SquareMile = "SquareMile";
    public static final java.lang.String _Thousand = "Thousand";
    public static final java.lang.String _Minute = "Minute";
    public static final java.lang.String _Million = "Million";
    public static final java.lang.String _MillionInternationalUnit = "MillionInternationalUnit";
    public static final java.lang.String _MilliardBillionUS = "MilliardBillionUS";
    public static final java.lang.String _Millilitre = "Millilitre";
    public static final java.lang.String _Milliliter = "Milliliter";
    public static final java.lang.String _SquareMillimetre = "SquareMillimetre";
    public static final java.lang.String _SquareMillimeter = "SquareMillimeter";
    public static final java.lang.String _CubicMillimetre = "CubicMillimetre";
    public static final java.lang.String _CubicMillimeter = "CubicMillimeter";
    public static final java.lang.String _Millimetre = "Millimetre";
    public static final java.lang.String _Millimeter = "Millimeter";
    public static final java.lang.String _Month = "Month";
    public static final java.lang.String _Megapascal = "Megapascal";
    public static final java.lang.String _CubicMetrePerHour = "CubicMetrePerHour";
    public static final java.lang.String _CubicMeterPerHour = "CubicMeterPerHour";
    public static final java.lang.String _CubicMetrePerSecond = "CubicMetrePerSecond";
    public static final java.lang.String _CubicMeterPerSecond = "CubicMeterPerSecond";
    public static final java.lang.String _MetrePerSecondSquared = "MetrePerSecondSquared";
    public static final java.lang.String _MeterPerSecondSquared = "MeterPerSecondSquared";
    public static final java.lang.String _SquareMetre = "SquareMetre";
    public static final java.lang.String _SquareMeter = "SquareMeter";
    public static final java.lang.String _CubicMetre = "CubicMetre";
    public static final java.lang.String _CubicMeter = "CubicMeter";
    public static final java.lang.String _Metre = "Metre";
    public static final java.lang.String _Meter = "Meter";
    public static final java.lang.String _MetrePerSecond = "MetrePerSecond";
    public static final java.lang.String _MeterPerSecond = "MeterPerSecond";
    public static final java.lang.String _MegavoltAmpere = "MegavoltAmpere";
    public static final java.lang.String _MegawattHour1000KWH = "MegawattHour1000KWH";
    public static final java.lang.String _NumberOfArticles = "NumberOfArticles";
    public static final java.lang.String _NumberOfBobbins = "NumberOfBobbins";
    public static final java.lang.String _NumberOfCells = "NumberOfCells";
    public static final java.lang.String _Newton = "Newton";
    public static final java.lang.String _NumberOfInternationalUnits = "NumberOfInternationalUnits";
    public static final java.lang.String _NauticalMile = "NauticalMile";
    public static final java.lang.String _NumberOfPacks = "NumberOfPacks";
    public static final java.lang.String _NumberOfParcels = "NumberOfParcels";
    public static final java.lang.String _NumberOfPairs = "NumberOfPairs";
    public static final java.lang.String _NumberOfParts = "NumberOfParts";
    public static final java.lang.String _NumberOfRolls = "NumberOfRolls";
    public static final java.lang.String _NetRegisterTon = "NetRegisterTon";
    public static final java.lang.String _Ohm = "Ohm";
    public static final java.lang.String _Ounce = "Ounce";
    public static final java.lang.String _FluidOunceUS = "FluidOunceUS";
    public static final java.lang.String _FluidOunceUK = "FluidOunceUK";
    public static final java.lang.String _Pascal = "Pascal";
    public static final java.lang.String _Piece = "Piece";
    public static final java.lang.String _ProofGallon = "ProofGallon";
    public static final java.lang.String _DryPintUS = "DryPintUS";
    public static final java.lang.String _PintUK = "PintUK";
    public static final java.lang.String _LiquidPintUS = "LiquidPintUS";
    public static final java.lang.String _QuarterOfAYear = "QuarterOfAYear";
    public static final java.lang.String _DryQuartUS = "DryQuartUS";
    public static final java.lang.String _QuartUK = "QuartUK";
    public static final java.lang.String _LiquidQuartUS = "LiquidQuartUS";
    public static final java.lang.String _QuarterUK = "QuarterUK";
    public static final java.lang.String _RevolutionsPerMinute = "RevolutionsPerMinute";
    public static final java.lang.String _RevolutionsPerSecond = "RevolutionsPerSecond";
    public static final java.lang.String _HalfYear6Months = "HalfYear6Months";
    public static final java.lang.String _Score = "Score";
    public static final java.lang.String _Scruple = "Scruple";
    public static final java.lang.String _Second = "Second";
    public static final java.lang.String _Set = "Set";
    public static final java.lang.String _ShippingTon = "ShippingTon";
    public static final java.lang.String _Siemens = "Siemens";
    public static final java.lang.String _MileStatuteMile = "MileStatuteMile";
    public static final java.lang.String _ShortStandard7200Matches = "ShortStandard7200Matches";
    public static final java.lang.String _StoneUK = "StoneUK";
    public static final java.lang.String _TonUSOrShortTonUKUS = "TonUSOrShortTonUKUS";
    public static final java.lang.String _KiloampereHourThousandAmpereHour = "KiloampereHourThousandAmpereHour";
    public static final java.lang.String _TonneMetricTon = "TonneMetricTon";
    public static final java.lang.String _TenPair = "TenPair";
    public static final java.lang.String _ThousandCubicMetrePerDay = "ThousandCubicMetrePerDay";
    public static final java.lang.String _ThousandCubicMeterPerDay = "ThousandCubicMeterPerDay";
    public static final java.lang.String _TrillionEUR = "TrillionEUR";
    public static final java.lang.String _TonneOfSubstance90PercentDry = "TonneOfSubstance90PercentDry";
    public static final java.lang.String _TonOfSteamPerHour = "TonOfSteamPerHour";
    public static final java.lang.String _Volt = "Volt";
    public static final java.lang.String _Cord = "Cord";
    public static final java.lang.String _Weber = "Weber";
    public static final java.lang.String _Week = "Week";
    public static final java.lang.String _WattHour = "WattHour";
    public static final java.lang.String _Standard = "Standard";
    public static final java.lang.String _Watt = "Watt";
    public static final java.lang.String _SquareYard = "SquareYard";
    public static final java.lang.String _CubicYard = "CubicYard";
    public static final java.lang.String _Yard = "Yard";
    public static final TypeUnitOfMeasure NotSet = new TypeUnitOfMeasure(_NotSet);
    public static final TypeUnitOfMeasure Acre = new TypeUnitOfMeasure(_Acre);
    public static final TypeUnitOfMeasure AmpereHour = new TypeUnitOfMeasure(_AmpereHour);
    public static final TypeUnitOfMeasure Ampere = new TypeUnitOfMeasure(_Ampere);
    public static final TypeUnitOfMeasure Year = new TypeUnitOfMeasure(_Year);
    public static final TypeUnitOfMeasure TroyOunceOrApothecariesOunce = new TypeUnitOfMeasure(_TroyOunceOrApothecariesOunce);
    public static final TypeUnitOfMeasure Are = new TypeUnitOfMeasure(_Are);
    public static final TypeUnitOfMeasure AlcoholicStrengthByMass = new TypeUnitOfMeasure(_AlcoholicStrengthByMass);
    public static final TypeUnitOfMeasure AlcoholicStrengthByVolume = new TypeUnitOfMeasure(_AlcoholicStrengthByVolume);
    public static final TypeUnitOfMeasure StandardAtmosphere = new TypeUnitOfMeasure(_StandardAtmosphere);
    public static final TypeUnitOfMeasure TechnicalAtmosphere = new TypeUnitOfMeasure(_TechnicalAtmosphere);
    public static final TypeUnitOfMeasure Bar = new TypeUnitOfMeasure(_Bar);
    public static final TypeUnitOfMeasure BoardFoot = new TypeUnitOfMeasure(_BoardFoot);
    public static final TypeUnitOfMeasure BrakeHorsePower = new TypeUnitOfMeasure(_BrakeHorsePower);
    public static final TypeUnitOfMeasure BillionEURTrillionUS = new TypeUnitOfMeasure(_BillionEURTrillionUS);
    public static final TypeUnitOfMeasure DryBarrelUS = new TypeUnitOfMeasure(_DryBarrelUS);
    public static final TypeUnitOfMeasure BarrelUSPetroleumEtc = new TypeUnitOfMeasure(_BarrelUSPetroleumEtc);
    public static final TypeUnitOfMeasure Becquerel = new TypeUnitOfMeasure(_Becquerel);
    public static final TypeUnitOfMeasure BritishThermalUnit = new TypeUnitOfMeasure(_BritishThermalUnit);
    public static final TypeUnitOfMeasure BushelUS = new TypeUnitOfMeasure(_BushelUS);
    public static final TypeUnitOfMeasure BushelUK = new TypeUnitOfMeasure(_BushelUK);
    public static final TypeUnitOfMeasure CarryingCapacityInMetricTon = new TypeUnitOfMeasure(_CarryingCapacityInMetricTon);
    public static final TypeUnitOfMeasure Candela = new TypeUnitOfMeasure(_Candela);
    public static final TypeUnitOfMeasure DegreeCelsius = new TypeUnitOfMeasure(_DegreeCelsius);
    public static final TypeUnitOfMeasure Hundred = new TypeUnitOfMeasure(_Hundred);
    public static final TypeUnitOfMeasure Centigram = new TypeUnitOfMeasure(_Centigram);
    public static final TypeUnitOfMeasure CoulombPerKilogram = new TypeUnitOfMeasure(_CoulombPerKilogram);
    public static final TypeUnitOfMeasure HundredLeave = new TypeUnitOfMeasure(_HundredLeave);
    public static final TypeUnitOfMeasure Centilitre = new TypeUnitOfMeasure(_Centilitre);
    public static final TypeUnitOfMeasure Centiliter = new TypeUnitOfMeasure(_Centiliter);
    public static final TypeUnitOfMeasure SquareCentimetre = new TypeUnitOfMeasure(_SquareCentimetre);
    public static final TypeUnitOfMeasure SquareCentimeter = new TypeUnitOfMeasure(_SquareCentimeter);
    public static final TypeUnitOfMeasure CubicCentimetre = new TypeUnitOfMeasure(_CubicCentimetre);
    public static final TypeUnitOfMeasure CubicCentimeter = new TypeUnitOfMeasure(_CubicCentimeter);
    public static final TypeUnitOfMeasure Centimetre = new TypeUnitOfMeasure(_Centimetre);
    public static final TypeUnitOfMeasure Centimeter = new TypeUnitOfMeasure(_Centimeter);
    public static final TypeUnitOfMeasure HundredPack = new TypeUnitOfMeasure(_HundredPack);
    public static final TypeUnitOfMeasure CentalUK = new TypeUnitOfMeasure(_CentalUK);
    public static final TypeUnitOfMeasure Coulomb = new TypeUnitOfMeasure(_Coulomb);
    public static final TypeUnitOfMeasure MetricCarat = new TypeUnitOfMeasure(_MetricCarat);
    public static final TypeUnitOfMeasure Curie = new TypeUnitOfMeasure(_Curie);
    public static final TypeUnitOfMeasure HundredPoundsCWTHundredWeightUS = new TypeUnitOfMeasure(_HundredPoundsCWTHundredWeightUS);
    public static final TypeUnitOfMeasure HundredWeightUK = new TypeUnitOfMeasure(_HundredWeightUK);
    public static final TypeUnitOfMeasure Decare = new TypeUnitOfMeasure(_Decare);
    public static final TypeUnitOfMeasure TenDay = new TypeUnitOfMeasure(_TenDay);
    public static final TypeUnitOfMeasure Day = new TypeUnitOfMeasure(_Day);
    public static final TypeUnitOfMeasure Decade = new TypeUnitOfMeasure(_Decade);
    public static final TypeUnitOfMeasure Decilitre = new TypeUnitOfMeasure(_Decilitre);
    public static final TypeUnitOfMeasure Deciliter = new TypeUnitOfMeasure(_Deciliter);
    public static final TypeUnitOfMeasure SquareDecimetre = new TypeUnitOfMeasure(_SquareDecimetre);
    public static final TypeUnitOfMeasure SquareDecimeter = new TypeUnitOfMeasure(_SquareDecimeter);
    public static final TypeUnitOfMeasure CubicDecimetre = new TypeUnitOfMeasure(_CubicDecimetre);
    public static final TypeUnitOfMeasure CubicDecimeter = new TypeUnitOfMeasure(_CubicDecimeter);
    public static final TypeUnitOfMeasure Decimetre = new TypeUnitOfMeasure(_Decimetre);
    public static final TypeUnitOfMeasure Decimeter = new TypeUnitOfMeasure(_Decimeter);
    public static final TypeUnitOfMeasure DozenPiece = new TypeUnitOfMeasure(_DozenPiece);
    public static final TypeUnitOfMeasure DozenPair = new TypeUnitOfMeasure(_DozenPair);
    public static final TypeUnitOfMeasure DisplacementTonnage = new TypeUnitOfMeasure(_DisplacementTonnage);
    public static final TypeUnitOfMeasure DramUS = new TypeUnitOfMeasure(_DramUS);
    public static final TypeUnitOfMeasure DramUK = new TypeUnitOfMeasure(_DramUK);
    public static final TypeUnitOfMeasure DozenRoll = new TypeUnitOfMeasure(_DozenRoll);
    public static final TypeUnitOfMeasure DrachmUK = new TypeUnitOfMeasure(_DrachmUK);
    public static final TypeUnitOfMeasure DecitonneCentnerMetric100KgQuintalMetric100Kg = new TypeUnitOfMeasure(_DecitonneCentnerMetric100KgQuintalMetric100Kg);
    public static final TypeUnitOfMeasure Pennyweight = new TypeUnitOfMeasure(_Pennyweight);
    public static final TypeUnitOfMeasure Dozen = new TypeUnitOfMeasure(_Dozen);
    public static final TypeUnitOfMeasure DozenPack = new TypeUnitOfMeasure(_DozenPack);
    public static final TypeUnitOfMeasure DegreeFahrenheit = new TypeUnitOfMeasure(_DegreeFahrenheit);
    public static final TypeUnitOfMeasure Farad = new TypeUnitOfMeasure(_Farad);
    public static final TypeUnitOfMeasure Foot = new TypeUnitOfMeasure(_Foot);
    public static final TypeUnitOfMeasure SquareFoot = new TypeUnitOfMeasure(_SquareFoot);
    public static final TypeUnitOfMeasure CubicFoot = new TypeUnitOfMeasure(_CubicFoot);
    public static final TypeUnitOfMeasure Gigabecquerel = new TypeUnitOfMeasure(_Gigabecquerel);
    public static final TypeUnitOfMeasure GramOfFissileIsotope = new TypeUnitOfMeasure(_GramOfFissileIsotope);
    public static final TypeUnitOfMeasure GreatGross = new TypeUnitOfMeasure(_GreatGross);
    public static final TypeUnitOfMeasure GillUS = new TypeUnitOfMeasure(_GillUS);
    public static final TypeUnitOfMeasure GillUK = new TypeUnitOfMeasure(_GillUK);
    public static final TypeUnitOfMeasure DryGallonUS = new TypeUnitOfMeasure(_DryGallonUS);
    public static final TypeUnitOfMeasure GallonUK = new TypeUnitOfMeasure(_GallonUK);
    public static final TypeUnitOfMeasure GallonUS = new TypeUnitOfMeasure(_GallonUS);
    public static final TypeUnitOfMeasure Gram = new TypeUnitOfMeasure(_Gram);
    public static final TypeUnitOfMeasure Grain = new TypeUnitOfMeasure(_Grain);
    public static final TypeUnitOfMeasure Gross = new TypeUnitOfMeasure(_Gross);
    public static final TypeUnitOfMeasure GrossRegisterTon = new TypeUnitOfMeasure(_GrossRegisterTon);
    public static final TypeUnitOfMeasure GigawattHour = new TypeUnitOfMeasure(_GigawattHour);
    public static final TypeUnitOfMeasure Hectare = new TypeUnitOfMeasure(_Hectare);
    public static final TypeUnitOfMeasure Hectobar = new TypeUnitOfMeasure(_Hectobar);
    public static final TypeUnitOfMeasure HundredBox = new TypeUnitOfMeasure(_HundredBox);
    public static final TypeUnitOfMeasure Hectogram = new TypeUnitOfMeasure(_Hectogram);
    public static final TypeUnitOfMeasure HundredInternationalUnit = new TypeUnitOfMeasure(_HundredInternationalUnit);
    public static final TypeUnitOfMeasure Hectolitre = new TypeUnitOfMeasure(_Hectolitre);
    public static final TypeUnitOfMeasure Hectoliter = new TypeUnitOfMeasure(_Hectoliter);
    public static final TypeUnitOfMeasure MillionCubicMetre = new TypeUnitOfMeasure(_MillionCubicMetre);
    public static final TypeUnitOfMeasure MillionCubicMeter = new TypeUnitOfMeasure(_MillionCubicMeter);
    public static final TypeUnitOfMeasure Hectometre = new TypeUnitOfMeasure(_Hectometre);
    public static final TypeUnitOfMeasure Hectometer = new TypeUnitOfMeasure(_Hectometer);
    public static final TypeUnitOfMeasure HectolitreOfPureAlcohol = new TypeUnitOfMeasure(_HectolitreOfPureAlcohol);
    public static final TypeUnitOfMeasure HectoliterOfPureAlcohol = new TypeUnitOfMeasure(_HectoliterOfPureAlcohol);
    public static final TypeUnitOfMeasure Hertz = new TypeUnitOfMeasure(_Hertz);
    public static final TypeUnitOfMeasure Hour = new TypeUnitOfMeasure(_Hour);
    public static final TypeUnitOfMeasure Inch = new TypeUnitOfMeasure(_Inch);
    public static final TypeUnitOfMeasure SquareInch = new TypeUnitOfMeasure(_SquareInch);
    public static final TypeUnitOfMeasure CubicInch = new TypeUnitOfMeasure(_CubicInch);
    public static final TypeUnitOfMeasure Joule = new TypeUnitOfMeasure(_Joule);
    public static final TypeUnitOfMeasure Kilobar = new TypeUnitOfMeasure(_Kilobar);
    public static final TypeUnitOfMeasure Kelvin = new TypeUnitOfMeasure(_Kelvin);
    public static final TypeUnitOfMeasure Kilogram = new TypeUnitOfMeasure(_Kilogram);
    public static final TypeUnitOfMeasure KilogramPerSecond = new TypeUnitOfMeasure(_KilogramPerSecond);
    public static final TypeUnitOfMeasure Kilohertz = new TypeUnitOfMeasure(_Kilohertz);
    public static final TypeUnitOfMeasure Kilojoule = new TypeUnitOfMeasure(_Kilojoule);
    public static final TypeUnitOfMeasure KilometrePerHour = new TypeUnitOfMeasure(_KilometrePerHour);
    public static final TypeUnitOfMeasure KilometerPerHour = new TypeUnitOfMeasure(_KilometerPerHour);
    public static final TypeUnitOfMeasure SquareKilometre = new TypeUnitOfMeasure(_SquareKilometre);
    public static final TypeUnitOfMeasure SquareKilometer = new TypeUnitOfMeasure(_SquareKilometer);
    public static final TypeUnitOfMeasure KilogramPerCubicMetre = new TypeUnitOfMeasure(_KilogramPerCubicMetre);
    public static final TypeUnitOfMeasure KilogramPerCubicMeter = new TypeUnitOfMeasure(_KilogramPerCubicMeter);
    public static final TypeUnitOfMeasure Kilometre = new TypeUnitOfMeasure(_Kilometre);
    public static final TypeUnitOfMeasure Kilometer = new TypeUnitOfMeasure(_Kilometer);
    public static final TypeUnitOfMeasure KilogramOfNitrogen = new TypeUnitOfMeasure(_KilogramOfNitrogen);
    public static final TypeUnitOfMeasure KilogramNamedSubstance = new TypeUnitOfMeasure(_KilogramNamedSubstance);
    public static final TypeUnitOfMeasure Knot = new TypeUnitOfMeasure(_Knot);
    public static final TypeUnitOfMeasure Kilopascal = new TypeUnitOfMeasure(_Kilopascal);
    public static final TypeUnitOfMeasure KilogramOfPotassiumHydroxideCausticPotash = new TypeUnitOfMeasure(_KilogramOfPotassiumHydroxideCausticPotash);
    public static final TypeUnitOfMeasure KilogramOfPotassiumOxide = new TypeUnitOfMeasure(_KilogramOfPotassiumOxide);
    public static final TypeUnitOfMeasure KilogramOfPhosphorusPentoxidePhosphoricAnhydride = new TypeUnitOfMeasure(_KilogramOfPhosphorusPentoxidePhosphoricAnhydride);
    public static final TypeUnitOfMeasure KilogramOfSubstance90PercentDry = new TypeUnitOfMeasure(_KilogramOfSubstance90PercentDry);
    public static final TypeUnitOfMeasure KilogramOfSodiumHydroxideCausticSoda = new TypeUnitOfMeasure(_KilogramOfSodiumHydroxideCausticSoda);
    public static final TypeUnitOfMeasure Kilotonne = new TypeUnitOfMeasure(_Kilotonne);
    public static final TypeUnitOfMeasure KilogramOfUranium = new TypeUnitOfMeasure(_KilogramOfUranium);
    public static final TypeUnitOfMeasure KilovoltAmpere = new TypeUnitOfMeasure(_KilovoltAmpere);
    public static final TypeUnitOfMeasure Kilovar = new TypeUnitOfMeasure(_Kilovar);
    public static final TypeUnitOfMeasure Kilovolt = new TypeUnitOfMeasure(_Kilovolt);
    public static final TypeUnitOfMeasure KilowattHour = new TypeUnitOfMeasure(_KilowattHour);
    public static final TypeUnitOfMeasure Kilowatt = new TypeUnitOfMeasure(_Kilowatt);
    public static final TypeUnitOfMeasure Pound = new TypeUnitOfMeasure(_Pound);
    public static final TypeUnitOfMeasure TroyPoundUS = new TypeUnitOfMeasure(_TroyPoundUS);
    public static final TypeUnitOfMeasure Leaf = new TypeUnitOfMeasure(_Leaf);
    public static final TypeUnitOfMeasure LitreOfPureAlcohol = new TypeUnitOfMeasure(_LitreOfPureAlcohol);
    public static final TypeUnitOfMeasure LiterOfPureAlcohol = new TypeUnitOfMeasure(_LiterOfPureAlcohol);
    public static final TypeUnitOfMeasure TonUKorLongTonUS = new TypeUnitOfMeasure(_TonUKorLongTonUS);
    public static final TypeUnitOfMeasure Litre = new TypeUnitOfMeasure(_Litre);
    public static final TypeUnitOfMeasure Liter = new TypeUnitOfMeasure(_Liter);
    public static final TypeUnitOfMeasure Lumen = new TypeUnitOfMeasure(_Lumen);
    public static final TypeUnitOfMeasure Lux = new TypeUnitOfMeasure(_Lux);
    public static final TypeUnitOfMeasure MegaLitre = new TypeUnitOfMeasure(_MegaLitre);
    public static final TypeUnitOfMeasure MegaLiter = new TypeUnitOfMeasure(_MegaLiter);
    public static final TypeUnitOfMeasure Megametre = new TypeUnitOfMeasure(_Megametre);
    public static final TypeUnitOfMeasure Megameter = new TypeUnitOfMeasure(_Megameter);
    public static final TypeUnitOfMeasure Megawatt = new TypeUnitOfMeasure(_Megawatt);
    public static final TypeUnitOfMeasure ThousandStandardBrickEquivalent = new TypeUnitOfMeasure(_ThousandStandardBrickEquivalent);
    public static final TypeUnitOfMeasure ThousandBoardFeet = new TypeUnitOfMeasure(_ThousandBoardFeet);
    public static final TypeUnitOfMeasure Millibar = new TypeUnitOfMeasure(_Millibar);
    public static final TypeUnitOfMeasure Millicurie = new TypeUnitOfMeasure(_Millicurie);
    public static final TypeUnitOfMeasure Milligram = new TypeUnitOfMeasure(_Milligram);
    public static final TypeUnitOfMeasure Megahertz = new TypeUnitOfMeasure(_Megahertz);
    public static final TypeUnitOfMeasure SquareMile = new TypeUnitOfMeasure(_SquareMile);
    public static final TypeUnitOfMeasure Thousand = new TypeUnitOfMeasure(_Thousand);
    public static final TypeUnitOfMeasure Minute = new TypeUnitOfMeasure(_Minute);
    public static final TypeUnitOfMeasure Million = new TypeUnitOfMeasure(_Million);
    public static final TypeUnitOfMeasure MillionInternationalUnit = new TypeUnitOfMeasure(_MillionInternationalUnit);
    public static final TypeUnitOfMeasure MilliardBillionUS = new TypeUnitOfMeasure(_MilliardBillionUS);
    public static final TypeUnitOfMeasure Millilitre = new TypeUnitOfMeasure(_Millilitre);
    public static final TypeUnitOfMeasure Milliliter = new TypeUnitOfMeasure(_Milliliter);
    public static final TypeUnitOfMeasure SquareMillimetre = new TypeUnitOfMeasure(_SquareMillimetre);
    public static final TypeUnitOfMeasure SquareMillimeter = new TypeUnitOfMeasure(_SquareMillimeter);
    public static final TypeUnitOfMeasure CubicMillimetre = new TypeUnitOfMeasure(_CubicMillimetre);
    public static final TypeUnitOfMeasure CubicMillimeter = new TypeUnitOfMeasure(_CubicMillimeter);
    public static final TypeUnitOfMeasure Millimetre = new TypeUnitOfMeasure(_Millimetre);
    public static final TypeUnitOfMeasure Millimeter = new TypeUnitOfMeasure(_Millimeter);
    public static final TypeUnitOfMeasure Month = new TypeUnitOfMeasure(_Month);
    public static final TypeUnitOfMeasure Megapascal = new TypeUnitOfMeasure(_Megapascal);
    public static final TypeUnitOfMeasure CubicMetrePerHour = new TypeUnitOfMeasure(_CubicMetrePerHour);
    public static final TypeUnitOfMeasure CubicMeterPerHour = new TypeUnitOfMeasure(_CubicMeterPerHour);
    public static final TypeUnitOfMeasure CubicMetrePerSecond = new TypeUnitOfMeasure(_CubicMetrePerSecond);
    public static final TypeUnitOfMeasure CubicMeterPerSecond = new TypeUnitOfMeasure(_CubicMeterPerSecond);
    public static final TypeUnitOfMeasure MetrePerSecondSquared = new TypeUnitOfMeasure(_MetrePerSecondSquared);
    public static final TypeUnitOfMeasure MeterPerSecondSquared = new TypeUnitOfMeasure(_MeterPerSecondSquared);
    public static final TypeUnitOfMeasure SquareMetre = new TypeUnitOfMeasure(_SquareMetre);
    public static final TypeUnitOfMeasure SquareMeter = new TypeUnitOfMeasure(_SquareMeter);
    public static final TypeUnitOfMeasure CubicMetre = new TypeUnitOfMeasure(_CubicMetre);
    public static final TypeUnitOfMeasure CubicMeter = new TypeUnitOfMeasure(_CubicMeter);
    public static final TypeUnitOfMeasure Metre = new TypeUnitOfMeasure(_Metre);
    public static final TypeUnitOfMeasure Meter = new TypeUnitOfMeasure(_Meter);
    public static final TypeUnitOfMeasure MetrePerSecond = new TypeUnitOfMeasure(_MetrePerSecond);
    public static final TypeUnitOfMeasure MeterPerSecond = new TypeUnitOfMeasure(_MeterPerSecond);
    public static final TypeUnitOfMeasure MegavoltAmpere = new TypeUnitOfMeasure(_MegavoltAmpere);
    public static final TypeUnitOfMeasure MegawattHour1000KWH = new TypeUnitOfMeasure(_MegawattHour1000KWH);
    public static final TypeUnitOfMeasure NumberOfArticles = new TypeUnitOfMeasure(_NumberOfArticles);
    public static final TypeUnitOfMeasure NumberOfBobbins = new TypeUnitOfMeasure(_NumberOfBobbins);
    public static final TypeUnitOfMeasure NumberOfCells = new TypeUnitOfMeasure(_NumberOfCells);
    public static final TypeUnitOfMeasure Newton = new TypeUnitOfMeasure(_Newton);
    public static final TypeUnitOfMeasure NumberOfInternationalUnits = new TypeUnitOfMeasure(_NumberOfInternationalUnits);
    public static final TypeUnitOfMeasure NauticalMile = new TypeUnitOfMeasure(_NauticalMile);
    public static final TypeUnitOfMeasure NumberOfPacks = new TypeUnitOfMeasure(_NumberOfPacks);
    public static final TypeUnitOfMeasure NumberOfParcels = new TypeUnitOfMeasure(_NumberOfParcels);
    public static final TypeUnitOfMeasure NumberOfPairs = new TypeUnitOfMeasure(_NumberOfPairs);
    public static final TypeUnitOfMeasure NumberOfParts = new TypeUnitOfMeasure(_NumberOfParts);
    public static final TypeUnitOfMeasure NumberOfRolls = new TypeUnitOfMeasure(_NumberOfRolls);
    public static final TypeUnitOfMeasure NetRegisterTon = new TypeUnitOfMeasure(_NetRegisterTon);
    public static final TypeUnitOfMeasure Ohm = new TypeUnitOfMeasure(_Ohm);
    public static final TypeUnitOfMeasure Ounce = new TypeUnitOfMeasure(_Ounce);
    public static final TypeUnitOfMeasure FluidOunceUS = new TypeUnitOfMeasure(_FluidOunceUS);
    public static final TypeUnitOfMeasure FluidOunceUK = new TypeUnitOfMeasure(_FluidOunceUK);
    public static final TypeUnitOfMeasure Pascal = new TypeUnitOfMeasure(_Pascal);
    public static final TypeUnitOfMeasure Piece = new TypeUnitOfMeasure(_Piece);
    public static final TypeUnitOfMeasure ProofGallon = new TypeUnitOfMeasure(_ProofGallon);
    public static final TypeUnitOfMeasure DryPintUS = new TypeUnitOfMeasure(_DryPintUS);
    public static final TypeUnitOfMeasure PintUK = new TypeUnitOfMeasure(_PintUK);
    public static final TypeUnitOfMeasure LiquidPintUS = new TypeUnitOfMeasure(_LiquidPintUS);
    public static final TypeUnitOfMeasure QuarterOfAYear = new TypeUnitOfMeasure(_QuarterOfAYear);
    public static final TypeUnitOfMeasure DryQuartUS = new TypeUnitOfMeasure(_DryQuartUS);
    public static final TypeUnitOfMeasure QuartUK = new TypeUnitOfMeasure(_QuartUK);
    public static final TypeUnitOfMeasure LiquidQuartUS = new TypeUnitOfMeasure(_LiquidQuartUS);
    public static final TypeUnitOfMeasure QuarterUK = new TypeUnitOfMeasure(_QuarterUK);
    public static final TypeUnitOfMeasure RevolutionsPerMinute = new TypeUnitOfMeasure(_RevolutionsPerMinute);
    public static final TypeUnitOfMeasure RevolutionsPerSecond = new TypeUnitOfMeasure(_RevolutionsPerSecond);
    public static final TypeUnitOfMeasure HalfYear6Months = new TypeUnitOfMeasure(_HalfYear6Months);
    public static final TypeUnitOfMeasure Score = new TypeUnitOfMeasure(_Score);
    public static final TypeUnitOfMeasure Scruple = new TypeUnitOfMeasure(_Scruple);
    public static final TypeUnitOfMeasure Second = new TypeUnitOfMeasure(_Second);
    public static final TypeUnitOfMeasure Set = new TypeUnitOfMeasure(_Set);
    public static final TypeUnitOfMeasure ShippingTon = new TypeUnitOfMeasure(_ShippingTon);
    public static final TypeUnitOfMeasure Siemens = new TypeUnitOfMeasure(_Siemens);
    public static final TypeUnitOfMeasure MileStatuteMile = new TypeUnitOfMeasure(_MileStatuteMile);
    public static final TypeUnitOfMeasure ShortStandard7200Matches = new TypeUnitOfMeasure(_ShortStandard7200Matches);
    public static final TypeUnitOfMeasure StoneUK = new TypeUnitOfMeasure(_StoneUK);
    public static final TypeUnitOfMeasure TonUSOrShortTonUKUS = new TypeUnitOfMeasure(_TonUSOrShortTonUKUS);
    public static final TypeUnitOfMeasure KiloampereHourThousandAmpereHour = new TypeUnitOfMeasure(_KiloampereHourThousandAmpereHour);
    public static final TypeUnitOfMeasure TonneMetricTon = new TypeUnitOfMeasure(_TonneMetricTon);
    public static final TypeUnitOfMeasure TenPair = new TypeUnitOfMeasure(_TenPair);
    public static final TypeUnitOfMeasure ThousandCubicMetrePerDay = new TypeUnitOfMeasure(_ThousandCubicMetrePerDay);
    public static final TypeUnitOfMeasure ThousandCubicMeterPerDay = new TypeUnitOfMeasure(_ThousandCubicMeterPerDay);
    public static final TypeUnitOfMeasure TrillionEUR = new TypeUnitOfMeasure(_TrillionEUR);
    public static final TypeUnitOfMeasure TonneOfSubstance90PercentDry = new TypeUnitOfMeasure(_TonneOfSubstance90PercentDry);
    public static final TypeUnitOfMeasure TonOfSteamPerHour = new TypeUnitOfMeasure(_TonOfSteamPerHour);
    public static final TypeUnitOfMeasure Volt = new TypeUnitOfMeasure(_Volt);
    public static final TypeUnitOfMeasure Cord = new TypeUnitOfMeasure(_Cord);
    public static final TypeUnitOfMeasure Weber = new TypeUnitOfMeasure(_Weber);
    public static final TypeUnitOfMeasure Week = new TypeUnitOfMeasure(_Week);
    public static final TypeUnitOfMeasure WattHour = new TypeUnitOfMeasure(_WattHour);
    public static final TypeUnitOfMeasure Standard = new TypeUnitOfMeasure(_Standard);
    public static final TypeUnitOfMeasure Watt = new TypeUnitOfMeasure(_Watt);
    public static final TypeUnitOfMeasure SquareYard = new TypeUnitOfMeasure(_SquareYard);
    public static final TypeUnitOfMeasure CubicYard = new TypeUnitOfMeasure(_CubicYard);
    public static final TypeUnitOfMeasure Yard = new TypeUnitOfMeasure(_Yard);
    public java.lang.String getValue() { return _value_;}
    public static TypeUnitOfMeasure fromValue(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        TypeUnitOfMeasure enumeration = (TypeUnitOfMeasure)
            _table_.get(value);
        if (enumeration==null) throw new java.lang.IllegalArgumentException();
        return enumeration;
    }
    public static TypeUnitOfMeasure fromString(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        return fromValue(value);
    }
    public boolean equals(java.lang.Object obj) {return (obj == this);}
    public int hashCode() { return toString().hashCode();}
    public java.lang.String toString() { return _value_;}
    public java.lang.Object readResolve() throws java.io.ObjectStreamException { return fromValue(_value_);}
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumSerializer(
            _javaType, _xmlType);
    }
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumDeserializer(
            _javaType, _xmlType);
    }
    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(TypeUnitOfMeasure.class);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Bankcard", "TypeUnitOfMeasure"));
    }
    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

}
